---
title: "case_study"
output: html_document
---

```{r setup}
library(p8105.datasets)

library(tidyverse)
library(ggridges)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%")
```

```{r airbnb}
data(nyc_airbnb)
```

## Airbnb

* Is price correlated with view score
* which neigborhood is the most popular
* which neigborhood highest review
* is availablity related to price
* is room type related to neigborhood
* is average length of stay related to neigborhood


```{r }
nyc_airbnb =
  nyc_airbnb %>%
  drop_na() %>%
  mutate(review_scores_location = review_scores_location/2,
         stars = as_factor(room_type),
         borough = neighbourhood_group)
```

### highest review?
```{r}
nyc_airbnb %>%
  group_by(neighbourhood_group) %>%
  ggplot(aes(x = neighbourhood_group, y = review_scores_location)) +
  geom_boxplot()

nyc_airbnb %>%
  group_by(neighbourhood_group) %>%
  summarise(mean_price = mean(price, na.rm = TRUE)) %>%
  arrange(mean_price)

nyc_airbnb %>%
  filter(borough == "Manhattan",
         price <= 1000) %>%
  ggplot(aes(x = neighbourhood, y = price)) +
  geom_boxplot() +
  cord_flip() +
  facet_grid(.~room_type)
```

Price v.s. location
```{r}
nyc_airbnb %>%
  sample_n(5000) %>%
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point()
```

### Is price correlated with view score

```{r}
nyc_airbnb %>%
  ggplot(aes(x = review_scores_location, y = price, color = neighbourhood_group)) +
  geom_point()


```

### Price and room type

```{r}
nyc_airbnb %>%
  ggplot(aes(x = stars, y = price)) +
  geom_point() +
  facet_grid(.~room_type)
```

### let's try leaflet

```{r, echo = FALSE}
pal <- colorFactor(c("navy", "red"), domain = c("ship", "pirate"))

library(leaflet)
nyc_airbnb %>% sample_n(5000) %>%
  leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>%
  addCircleMarkers(~lat, ~long, radius = 1, color = ~pal(stars))
```






